In [2]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import average, cophenet, linkage
from scipy.stats import kendalltau, rankdata

### Compute Distance Matrices

load PPR matrices (of size k x k) from file and compute hierachical clusterings + distances:
- exact sparsifier
- induced subgraph
- elimstar approximate
- randomclique approximate

In [ ]:
file_dir = "./PPR-matrices/deezer/"
exact_RN = np.loadtxt(file_dir + "deezer_exact_RN.txt")
PPR_induced_RN = np.loadtxt(file_dir + "deezer_induced_RN.txt")
approx_ES_10_10_RN = np.loadtxt(file_dir + "deezer_spiel_10_10_RN.txt")
approx_RC_10_10_RN = np.loadtxt(file_dir + "deezer_kyng_10_10_RN.txt")

# cosine and average appear to work best
D_exact_RN = pdist(exact_RN, metric='cosine')
D_PPR_induced_RN = pdist(PPR_induced_RN, metric='cosine')
D_approx_ES_10_10_RN = pdist(approx_ES_10_10_RN, metric='cosine')
D_approx_RC_10_10_RN = pdist(approx_RC_10_10_RN, metric='cosine')

# compute hierachical clustering
Z_exact_RN = linkage(D_exact_RN, method='average')  
Z_PPR_induced_RN = linkage(D_PPR_induced_RN, method='average')    
Z_approx_ES_10_10_RN = linkage(D_approx_ES_10_10_RN, method='average')  
Z_approx_RC_10_10_RN = linkage(D_approx_RC_10_10_RN, method='average')  

# and cophenetic distance
coph_exact_RN = cophenet(Z_exact_RN)
coph_matrix_exact_RN = squareform(coph_exact_RN)
coph_PPR_induced_RN = cophenet(Z_PPR_induced_RN)
coph_matrix_PPR_induced_RN = squareform(coph_PPR_induced_RN)
coph_approx_ES_10_10_RN = cophenet(Z_approx_ES_10_10_RN)
coph_matrix_approx_ES_10_10_RN = squareform(coph_approx_ES_10_10_RN)
coph_approx_RC_10_10_RN = cophenet(Z_approx_RC_10_10_RN)
coph_matrix_approx_RC_10_10_RN = squareform(coph_approx_RC_10_10_RN)

### Compute Clustering Metrics

Jaccard Index between top10 nodes in exact and approximate sparsifier

In [4]:
# exact vs induced

jacs = []

# for each node in sparsifier
for i in range(1000):
    # find top ten closest nodes in exact sparsifier H
    top10_H = np.argsort(coph_matrix_exact_RN[i])[1:11]
    # find top ten closest nodes in induced/approximate sparsifier
    top10_approx = np.argsort(coph_matrix_PPR_induced_RN[i])[1:11]
    print(top10_H)
    print(top10_approx)

    set1 = set(top10_H)
    set2 = set(top10_approx)
    intersection = set1 & set2
    union = set1 | set2
    jac = len(intersection) / len(union) if union else 0.0
    print(jac)
    jacs.append(jac)

mean_j = np.mean(jacs)
print(mean_j)

[507 440   3 283 629 745 731 157 286 679]
[658 659 660 661 662 663 664 665 666 667]
0.0
[ 65 472 471 468 435 376 684 700 356 770]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[549 299 632 643 651 265 263 179 510 976]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[  0 507 440 283 629 745 731 157 286 679]
[  0 658 659 660 661 662 663 664 665 666]
0.05263157894736842
[375 339 509 469  53 545 330  27 970 219]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[286 679 890 157 731 490 447 314 315 495]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[329 752 650 853 657 834 222 113 253 209]
[329   0 659 660 661 662 663 664 665 666]
0.05263157894736842
[500 851 121 793 319 191 625 558 530 555]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[987 584 577 496  55 422 425 428 393 433]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[183 704 772 795 304 565 105 483 607 603]
[  0 658 659 660 661 662 663 664 665 666]
0.0
[724 603 607 980 483 195 744  15 573 736]
[  0 658 659 660 661 662 663 664 665 666]
0.0


In [5]:
# exact vs elimstar

jacs = []

# for each node in sparsifier
for i in range(1000):
    # find top ten closest nodes in exact sparsifier H
    top10_H = np.argsort(coph_matrix_exact_RN[i])[1:11]
    # find top ten closest nodes in induced/approximate sparsifier
    top10_approx = np.argsort(coph_matrix_approx_ES_10_10_RN[i])[1:11]
    print(top10_H)
    print(top10_approx)

    set1 = set(top10_H)
    set2 = set(top10_approx)
    intersection = set1 & set2
    union = set1 | set2
    jac = len(intersection) / len(union) if union else 0.0
    print(jac)
    jacs.append(jac)

mean_j = np.mean(jacs)
print(mean_j)

[507 440   3 283 629 745 731 157 286 679]
[450 720  37 669 222 593 476 169 852 654]
0.0
[ 65 472 471 468 435 376 684 700 356 770]
[325 468 435 572  65 770 700 684 531 324]
0.42857142857142855
[549 299 632 643 651 265 263 179 510 976]
[510 643 976 651 299 265 263  43 144 918]
0.5384615384615384
[  0 507 440 283 629 745 731 157 286 679]
[172 891 514 638  11 969  44 159 859 221]
0.0
[375 339 509 469  53 545 330  27 970 219]
[ 33 644 779 236 793 759 910 530 851 500]
0.0
[286 679 890 157 731 490 447 314 315 495]
[890 679 286 157 490 731 315 397 495 554]
0.6666666666666666
[329 752 650 853 657 834 222 113 253 209]
[329 752 113 657 853 650 834 309 804 790]
0.5384615384615384
[500 851 121 793 319 191 625 558 530 555]
[851 500 384 793 984 807 530 910 555 876]
0.3333333333333333
[987 584 577 496  55 422 425 428 393 433]
[987 584 543  87 758 960 796 444 457 619]
0.1111111111111111
[183 704 772 795 304 565 105 483 607 603]
[183 393 366 738 458 836 899 106 524 247]
0.05263157894736842
[724 603 607 

In [6]:
# exact vs randomclique

jacs = []

# for each node in sparsifier
for i in range(1000):
    # find top ten closest nodes in exact sparsifier H
    top10_H = np.argsort(coph_matrix_exact_RN[i])[1:11]
    # find top ten closest nodes in induced/approximate sparsifier
    top10_approx = np.argsort(coph_matrix_approx_RC_10_10_RN[i])[1:11]
    print(top10_H)
    print(top10_approx)

    set1 = set(top10_H)
    set2 = set(top10_approx)
    intersection = set1 & set2
    union = set1 | set2
    jac = len(intersection) / len(union) if union else 0.0
    print(jac)
    jacs.append(jac)

mean_j = np.mean(jacs)
print(mean_j)

[507 440   3 283 629 745 731 157 286 679]
[783 904 861 647 363 624 117 815  67 150]
0.0
[ 65 472 471 468 435 376 684 700 356 770]
[499 468 465 461 445 442 441 435 433 428]
0.1111111111111111
[549 299 632 643 651 265 263 179 510 976]
[632 263 651 299 179 119 770 265 684  43]
0.42857142857142855
[  0 507 440 283 629 745 731 157 286 679]
[ 28 440 507 426 455 550 586 130 157 731]
0.25
[375 339 509 469  53 545 330  27 970 219]
[375 384 490 575 146 857 507 426 586  28]
0.05263157894736842
[286 679 890 157 731 490 447 314 315 495]
[890 286 679 157 447 731 495 315 426 455]
0.6666666666666666
[329 752 650 853 657 834 222 113 253 209]
[329 752 804 657 853 650 834 222  98 253]
0.6666666666666666
[500 851 121 793 319 191 625 558 530 555]
[851 500 204 446 727 264 585 372 339 870]
0.1111111111111111
[987 584 577 496  55 422 425 428 393 433]
[987 584  87 444 543  26 809 619 796 457]
0.1111111111111111
[183 704 772 795 304 565 105 483 607 603]
[183 140 484 114 549  66 244 552 553 879]
0.05263157894736

### Taus

we also tried to compare clustering using kedall tau and tested different ways of comparing top10 but did not get something useful

In [7]:
taus = []
# for each node in sparsifier
for i in range(1000):
    # find top ten closest nodes in H (excluding i)
    top10_H = np.argsort(coph_matrix_exact_RN[i])[1:11]
    # get ordering in approximate sparsifier (can also swap the order of the steps)
    top10_approx = np.argsort([coph_matrix_PPR_induced_RN[i][j] for j in top10_H])
    # since we can have ties we should use a function that can handle ties
    # print(rankdata([coph_matrix_PPR_induced_RN[i][j] for j in top10_H]))
    tau, _ = kendalltau(rankdata([coph_matrix_exact_RN[i][j] for j in top10_H]), rankdata([coph_matrix_PPR_induced_RN[i][j] for j in top10_H]))
    taus.append(tau)

mean_tau = np.mean(taus)
print(mean_tau)

nan


### Clustering in G

For LastFM graph we additinally computed PPR matrix of input graph G and repeated experiment from above (is only feasible for smallish graphs)

In [9]:
# load PPR_G from file
PPR_G = np.loadtxt("./PPR-matrices/lastfm/PPR_G.txt")
D_G = pdist(PPR_G, metric='cosine')
Z_G = linkage(D_G, method='average')  
coph_G = cophenet(Z_G)
coph_matrix_G = squareform(coph_G)

In [14]:
# mapping from sparsifier to exact
map_H_to_G_RN = np.loadtxt("./PPR-matrices/lastfm/lastfm_map.txt", dtype=int)

exact_RN = np.loadtxt("./PPR-matrices/lastfm/exact_RN.txt")
D_exact_RN = pdist(exact_RN, metric='cosine')
Z_exact_RN = linkage(D_exact_RN, method='average')  
coph_exact_RN = cophenet(Z_exact_RN)
coph_matrix_exact_RN = squareform(coph_exact_RN)

In [15]:
jacs = []
# for each node in sparsifier
for i in range(1000):
    # find top ten closest nodes in sparsifier
    top10_H = np.argsort(coph_matrix_exact_RN[i])[1:11]
    # map indices from sparsifier to G and find top10 terminal nodes in G
    top10_G = np.argsort([coph_matrix_G[map_H_to_G_RN[i]][j] for j in map_H_to_G_RN])[1:11]

    print(top10_H)
    print(top10_G)

    set1 = set(top10_H)
    set2 = set(top10_G)
    intersection = set1 & set2
    union = set1 | set2
    jac = len(intersection) / len(union) if union else 0.0
    print(jac)
    jacs.append(jac)

mean_j = np.mean(jacs)
print(mean_j)

[846 432 718 591 347 120 671 650 999  39]
[392  68 600 604 938  65 378  86  91 102]
0.0
[375 965 800  69  77 524  76 759 107 290]
[375 408 469  76 800  35 465 181 460 575]
0.17647058823529413
[573 969 663 635 597 363 993  24 990 301]
[573 635 597 624 935 993 363 990 148  24]
0.5384615384615384
[ 83 418 276 546 201 974  80  87 420 396]
[ 83 418 299 827 999 610 607 595 125 130]
0.1111111111111111
[313  72 576 337 100 919 917  96  30 422]
[313  72  76 828  35 792  77 524 317 623]
0.1111111111111111
[519 824 900 285 946 850 192 392 704 641]
[519 354 111 394 105  77 182  72 931  69]
0.05263157894736842
[518 881 193 351 504 321 390 270 859 410]
[105 291  77 182  72 931  69 246 185 187]
0.0
[611 843 443 397 814 902 385 229 216  60]
[162 452  36 296 826 424 319 265 590 390]
0.0
[243 611 843 443 397 814 902 385 229 216]
[243 510 832 936 597 749 371 135 736 904]
0.05263157894736842
[293 257 532 598 745 683 471 737 803 585]
[532 382 490 878 877 585  33 734 866 414]
0.1111111111111111
[743 147 727